version: '3'

services:
  db:
    container_name: postgres-db
    image: postgres
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      - postgres-net
    
  pgAdmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    networks:
      - postgres-net

# volumes:
#   postgres-db:
#     external: true

networks:
  postgres-net:
    external: true
